import "./globals.css";
import type { Metadata } from "next";
import Providers from "./providers";
import Sidebar from "./components/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <main className="flex bg-gray-100">
            <Sidebar />
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
